Rename step IDs, disable Terraform plan step, rename plan output file, fix PR comments and plan step status

diff --git a/.github/workflows/terraform-pr.yml b/.github/workflows/terraform-pr.yml
--- a/.github/workflows/terraform-pr.yml
+++ b/.github/workflows/terraform-pr.yml
@@ -1,5 +1,3 @@
-# TODO: break workflow in 2 stages (jobs) - validate and plan
-
 name: 'Terraform-PR'
 
 on:
@@ -56,7 +54,7 @@ jobs:
 
       # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
       - name: Terraform Init
-        id: tf_init
+        id: init
         env:
           ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
           ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
@@ -67,15 +65,15 @@ jobs:
           CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
         run: terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP"
 
-      # Run terraform validate
-      - name: Terraform Validate
-        id: tf_validate
-        # if: github.ref != 'refs/heads/main' && (success() || failure()) # Disabled for the time being
-        run: terraform validate -no-color
+      # # Run terraform validate
+      # - name: Terraform Validate
+      #   id: validate
+      #   # if: github.ref != 'refs/heads/main' && (success() || failure()) # Disabled for the time being
+      #   run: terraform validate -no-color
 
       # Run terragrunt validate
       - name: Terragrunt Validate
-        id: tg_validate
+        id: validate
         # if: github.ref != 'refs/heads/main' && (success() || failure())
         run: terragrunt run-all validate
 
@@ -133,15 +131,25 @@ jobs:
           job_summary: true
           check_name: Checkov Module Test Results
 
-      - name: Terraform Plan
-        id: tf_plan
+      # - name: Terraform Plan
+      #   id: plan
+      #   env:
+      #     ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
+      #     ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
+      #     ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
+      #     ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
+      #   # if: github.event_name == 'pull_request' # Disabled for the time being
+      #   run: terraform plan -no-color -out=$GITHUB_WORKSPACE/tf_plan.json
+
+      - name: Terragrunt Plan
+        id: plan
         env:
           ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
           ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
           ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
           ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
         # if: github.event_name == 'pull_request' # Disabled for the time being
-        run: terraform plan -no-color -out=$GITHUB_WORKSPACE/terraform.json
+        run: terragrunt run-all plan -no-color -out=$GITHUB_WORKSPACE/tf_plan.json
 
       # Verify Terraform plan file with Checkov
       - name: Checkov Verify Plan
@@ -149,7 +157,7 @@ jobs:
         uses: bridgecrewio/checkov-action@master
         with:
           # directory: .
-          file: $GITHUB_WORKSPACE/terraform.json # optional: provide the path for resource to be scanned. This will override the directory if both are provided.
+          file: $GITHUB_WORKSPACE/tf_plan.json # optional: provide the path for resource to be scanned. This will override the directory if both are provided.
           # check: CKV_AZURE_14 # optional: run only a specific check_id. can be comma separated list
           # skip_check: CKV_AWS_2 # optional: skip a specific check_id. can be comma separated list
           # quiet: true # optional: display only failed checks
@@ -180,45 +188,46 @@ jobs:
           job_summary: true
           check_name: Checkov Plan Test Results
 
-      # # Insert plan as pull request comments
-      # - uses: actions/github-script@v6
-      #   # if: github.event_name == 'pull_request' # Disabled for the time being
-      #   env:
-      #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-      #   with:
-      #     github-token: ${{ secrets.GITHUB_TOKEN }}
-      #   # with:
-      #   #   github-token: ${{ secrets.GITHUB_TOKEN }} # Should not be needed
-      #     script: |
-      #       const output = `#### Terraform format and style: \`${{ steps.fmt.outcome }}\`
-      #       #### Terraform initialization: \`${{ steps.init.outcome }}\`
-      #       #### Terraform validation: \`${{ steps.validate.outcome }}\`
-      #       #### Terraform plan: \`${{ steps.plan.outcome }}\`
+      # Insert Terraform plan as pull request comments
+      - uses: actions/github-script@v6
+        # if: github.event_name == 'pull_request' # Disabled for the time being
+        env:
+          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+        # with:
+        #   github-token: ${{ secrets.GITHUB_TOKEN }} # Should not be needed
+          script: |
+            const output = `#### Terraform format and style: \`${{ steps.tf_fmt.outcome }}\`
+            #### Terragrunt format and style: \`${{ steps.tg_hclfmt.outcome }}\`
+            #### Terraform initialization: \`${{ steps.init.outcome }}\`
+            #### Terraform validation: \`${{ steps.validate.outcome }}\`
+            #### Terraform plan: \`${{ steps.plan.outcome }}\`
 
-      #       <details><summary>Show Plan</summary>
+            <details><summary>Show Plan</summary>
 
-      #       \`\`\`\n
-      #       ${process.env.PLAN}
-      #       \`\`\`
+            \`\`\`\n
+            ${process.env.PLAN}
+            \`\`\`
 
-      #       </details>
+            </details>
 
-      #       *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
 
-      #       github.rest.issues.createComment({
-      #         issue_number: context.issue.number,
-      #         owner: context.repo.owner,
-      #         repo: context.repo.repo,
-      #         body: output
-      #       })
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: output
+            })
 
-      # - name: Terraform Plan Status
-      #   if: steps.plan.outcome == 'failure'
-      #   run: exit 1
+      - name: Terraform Plan Status
+        if: steps.plan.outcome == 'failure'
+        run: exit 1
 
-      # # Upload plan file as build artifact
+      # Upload plan file as build artifact
 
-      # - uses: actions/upload-artifact@v3
-      #   with:
-      #     name: terraform-plan
-      #     path: ${{ github.workspace }}/terraform.tfplan
+      - uses: actions/upload-artifact@v3
+        with:
+          name: terraform-plan
+          path: ${{ github.workspace }}/tf_plan.json
